service: telegrambotaaf

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 128

  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    DEBUG: ${env:DEBUG_LOG}

functions:
  entry:
    handler: handler.entry
    timeout: 60
    events:
    - http:
        path: /
        method: POST
        cors: true

plugins:
  - serverless-offline